project_id  = "yoda-data-2026"
environment = "dev"
region      = "europe-west1"
# bi_readers_group     = "bi-readers-dev@bpce-assurances.example"
# data_engineers_group = "data-engineers@bpce-assurances.example"
